opentelemetry-collector:
  resources:
    limits:
      memory: 512Mi
components:
  frontendProxy:
    service:
      type: LoadBalancer
    resources:
      limits:
        memory: 256Mi
  featureflagService:
    resources:
      limits:
        memory: 2048Mi
