---
apiVersion: v1
kind: Service
metadata:
  name: windows-vnc
spec:
  type: LoadBalancer
  selector:
    name: windows
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006

