certmanager:
  install: false
gitlab-runner:
  runners:
    privileged: true
global:
  appConfig:
    omniauth:
      enabled: true
      providers:
      - key: google_oauth2
        secret: gitlab-google-oauth2
  edition: ce
  hosts:
    domain: cloud.qbo.io
  ingress:
    configureCertmanager: false
    tls:
      secretName: wildcard-tls
  pages:
    accessControl: true
    enabled: true
    host: cloud.qbo.io
minio:
  persistence:
    size: 100G
