#!/usr/bin/env bash

#################################
# include -=qbot=-
# you can pass command line args
#
# example:
# to disable simulated typing
# . ../qbo.sh -d
#
# pass -h to see all options
#################################
shopt -s expand_aliases
. ../qbot.sh

NAME=$USER


if type getent > /dev/null 2>&1; then
        g=$(getent group docker | awk -F ':' '{print $3}')
else
        g=$(cat /etc/group | grep docker: | awk -F ':' '{print $3}')
fi


########################
# Configure the options
########################
#
# speed at which to simulate typing. bigger num = faster
#
# TYPE_SPEED=20
#
# custom prompt
#
# see http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html for escape sequences
#

usage() {

	echo "$0 gce {instance_name}"
        exit 1
}


if [ "$1" != "qke" ]; then
	usage

fi

#if [ -z "$2" ]; then
#        usage
#fi


DEMO_PROMPT="\e[0;38;5;231;48;5;31;1m (qb) \e[0;38;5;31;48;5;236;22m \e[0;38;5;250;48;5;236m qbot \e[0;38;5;236;48;5;31;1m\e[0;38;5;231;48;5;31;1m $1 \e[0;38;5;31;1m \e[0m"

# hide the evidence
#clear
printf "\033c"
alias qbo=cli

pe "qbo version | jq .version[]?"
# ADD CLUSTER
pe "qbo add cluster $NAME | jq"
pe "qbo get nodes $NAME | jq '.nodes[]?'"

V=$(qbo version | jq -r '.version[]?.qbo | select( . != null)')
CE="api-.*:ce-"
if [[ "$V" =~ $CE ]]; then
       V="ce"
else
       V="cloud"
fi

if [ "$V" = "ce" ]; then
        pe "export KUBECONFIG=/tmp/qbo/$NAME.conf"
else
        pe "qbo get cluster $NAME -k | jq -r '.output[]?.kubeconfig | select( . != null)' > $HOME/.qbo/$NAME.conf"
        pe "export KUBECONFIG=$HOME/.qbo/$NAME.conf"
fi
pe "kubectl get nodes"

# ADD NODE
pe "qbo add node -n3 $NAME | jq"
if [ "$V" = "ce" ]; then
	pe "watch kubectl get nodes"
fi
# STOP CLUSTER
pe "qbo stop cluster $NAME | jq"

# START CLUSTER
pe "qbo start cluster $NAME | jq"
if [ "$V" = "ce" ]; then
	pe "watch kubectl get nodes"
	pe "watch kubectl get pods -n kube-system"
fi

# STOP CLUSTER
NODE=$(qbo get node alex | jq -r .nodes[]?.name | head -1)
pe "qbo stop node $NODE | jq"
if [ "$V" = "ce" ]; then
	pe "watch kubectl get nodes"
fi
# START NODE
pe "qbo start node $NODE | jq"
if [ "$V" = "ce" ]; then
	pe "watch kubectl get nodes"
        pe "watch kubectl get pods -n kube-system"
fi

# DELETE NODE
pe "qbo delete node $NODE | jq"
if [ "$V" = "ce" ]; then
	pe "watch kubectl get nodes"
fi
# DELETE CLUSTER
pe "qbo delete cluster $NAME | jq"

# show a prompt so as not to reveal our true nature after
# the demo has concluded
p ""
