#!/usr/bin/env bash

#################################
# include -=qbot=-
# you can pass command line args
#
# example:
# to disable simulated typing
# . ../qbo.sh -d
#
# pass -h to see all options
#################################
shopt -s expand_aliases
. ../qbot.sh

NAME=$USER


if type getent > /dev/null 2>&1; then
        g=$(getent group docker | awk -F ':' '{print $3}')
else
        g=$(cat /etc/group | grep docker: | awk -F ':' '{print $3}')
fi


########################
# Configure the options
########################
#
# speed at which to simulate typing. bigger num = faster
#
# TYPE_SPEED=20
#
# custom prompt
#
# see http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html for escape sequences
#

usage() {

	echo "$0 plasma"
        exit 1
}


if [ "$1" != "plasma" ]; then
	usage

fi


NAME=$USER

DEMO_PROMPT="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

# hide the evidence
#clear
printf "\033c"

pe "glxgears -info"
pe "vlc -f wakeup.mp4"
pe "/usr/games/etr"

#BIN=$(find $HOME/cuda-samples/bin/x86_64/linux/release/ -maxdepth 1 -type f ! -name "*.*" -perm -og+rx)
#for i in $BIN; do
#	pe "$i"
#done

# show a prompt so as not to reveal our true nature after
# the demo has concluded
p ""
