apiVersion: v1
kind: Service
metadata:
  name: clickhouse-simple-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    clickhouse.altinity.com/chi: simple-01
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: native

