apiVersion: v1
kind: Service
metadata:
  name: redpanda-loadbalancer
  namespace: redpanda
spec:
  selector:
    app: redpanda
  ports:
    - name: port-9645
      protocol: TCP
      port: 9645             # External LoadBalancer port
      targetPort: 9645       # Redpanda internal port
    - name: port-9094
      protocol: TCP
      port: 31092
      targetPort: 9094
    - name: port-8083
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: port-8084
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer
