apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef:
    chartVersion: 5.9.19
  clusterSpec:
    fullnameOverride: <custom-hostname>
    external:
      enabled: true
      type: LoadBalancer
      domain: cloud.eadem.com
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: secretpassword
    statefulset:
      initContainers:
        setDataDirOwnership:
          enabled: true
