#!/usr/bin/env bash

#################################
# include -=qbot=-
# you can pass command line args
#
# example:
# to disable simulated typing
# . ../qbo.sh -d
#
# pass -h to see all options
#################################
shopt -s expand_aliases
. ../qbot.sh

NAME=alex
REGISTRY=registry.eadem.com
REPO=qbo-cli
IMAGE=$REGISTRY/$NAME/$REPO/qbo-cli


if type getent > /dev/null 2>&1; then
        g=$(getent group docker | awk -F ':' '{print $3}')
else
        g=$(cat /etc/group | grep docker: | awk -F ':' '{print $3}')
fi


########################
# Configure the options
########################
#
# speed at which to simulate typing. bigger num = faster
#
# TYPE_SPEED=20
#
# custom prompt
#
# see http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html for escape sequences
#

if [ -z "$2" ]; then
        echo "$0 {name}"
        exit 1
fi

NAME=$2

DEMO_PROMPT="\e[0;38;5;231;48;5;31;1m (qb) \e[0;38;5;31;48;5;236;22m \e[0;38;5;250;48;5;236m qbot \e[0;38;5;236;48;5;31;1m\e[0;38;5;231;48;5;31;1m $1 \e[0;38;5;31;1m \e[0m"

# hide the evidence
#clear
printf "\033c"
alias qbo=cli
pei "qbo version | jq .version[]?"
pei "qbo get nodes $NAME | jq '.nodes[]?'"

V=$(qbo version | jq -r '.version[]?.qbo | select( . != null)')
CE="api-.*:ce-"
if [[ "$V" =~ $CE ]]; then
       V="ce"
else
       V="cloud"
fi

if [ "$V" = "ce" ]; then
	pei "export KUBECONFIG=/tmp/qbo/$NAME.conf"
else
	pei "qbo get cluster $NAME -k | jq -r '.output[]?.kubeconfig | select( . != null)' > $HOME/.qbo/$NAME.conf"
	pei "export KUBECONFIG=$HOME/.qbo/$NAME.conf"
fi 
pei "kubectl get nodes"

# show a prompt so as not to reveal our true nature after
# the demo has concluded
p ""
