apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration: 
      featureGates:
        - GPU
        - DisableMDEVConfiguration
    permittedHostDevices:
       pciHostDevices:
       - externalResourceProvider: true
         pciVendorSelector: "10DE:1FB9"
         resourceName: "nvidia.com/TU117GLM_QUADRO_T1000_MOBILE"
