apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - name: s3-api      # Required name for the first port
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console     # Required name for the second port (MinIO Web UI)
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: minio
