apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  labels:
    app: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx-1
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1
spec:
  type: LoadBalancer
  selector:
    app: nginx-1
  ports:
  - protocol: TCP
    port: 80        # Exposed port
    targetPort: 80  # Port on the Nginx container

